name: pull-request-validation

on:
  pull_request:
    branches:
      - "*"

jobs:
  test-xcode26-beta:
    name: Build and Test with Xcode 26 Beta / Swift 6.2
    runs-on: macos-15
    env:
      MOCKABLE_LINT: true
      MOCKABLE_TEST: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 26 (Swift 6.2)
        run: |
          sudo xcode-select -s /Applications/Xcode_26.0.app
          swift -version

      - name: Show versions
        run: |
          echo "Xcode version:"
          xcodebuild -version
          echo ""
          echo "Swift version:"
          swift --version

      - name: Run Tests
        run: |
          Scripts/lint.sh & Scripts/test.sh
