name: pull-request-validation

on:
  pull_request:
    branches:
      - "*"

jobs:
  test-swift-6-2:
    name: Build and Test with Swift 6.2
    runs-on: macos-latest
    env:
      MOCKABLE_LINT: true
      MOCKABLE_TEST: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Show versions
        run: |
          echo "Xcode version:"
          xcodebuild -version
          echo ""
          echo "Swift version:"
          swift --version
          echo ""
          echo "Checking for Swift 6.2:"
          swift --version | grep -E "6\.[2-9]|7\." || echo "Swift 6.2 not found, using available version"

      - name: Run Tests
        run: |
          Scripts/lint.sh & Scripts/test.sh
