name: pull-request-validation

on:
  pull_request:
    branches:
      - "*"

jobs:
  test-xcode26-beta:
    name: Build and Test with Xcode 26 Beta / Swift 6.2
    runs-on: macos-latest
    env:
      MOCKABLE_LINT: true
      MOCKABLE_TEST: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode 26 Beta
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26-beta'
        continue-on-error: true

      - name: Show versions
        run: |
          echo "Xcode version:"
          xcodebuild -version
          echo ""
          echo "Swift version:"
          swift --version

      - name: Run Tests
        run: |
          Scripts/lint.sh & Scripts/test.sh
